export const COLORS = {
  backgroundColor: '#ffffff',
  black: '#000000',
  grey: '#ABABAB',
  blue: '#189EFF',
  white: '#FFFFFF',
  textColor: '#151313',
  textColorGrey: '#969696',
  error: '#FE0303',
  green: '#4CCF0F',
  red: '#FE0303',
  placeholder: '#BABABA',
};

export const images = {
  backButton: require('../../assets/backButton.png'),
  headerIcon: require('../../assets/headerIcon.png'),
  bigAppIcon: require('../../assets/BigAppIcon.png'),
  cameraIcon: require('../../assets/cameraIcon.png'),
  dummyProfilePic: require('../../assets/dummyProfilePic.png'),
  profileSelected: require('../../assets/porfileSelected.png'),
  profileUnselected: require('../../assets/profileUnselected.png'),
  communitySelected: require('../../assets/communitySelected.png'),
  communityUnselected: require('../../assets/communityUnselected.png'),
  search: require('../../assets/Search.png'),
  filter: require('../../assets/Filter.png'),
  postOptions: require('../../assets/postOptions.png'),
  commentsIcon: require('../../assets/Comment.png'),
  likeIcon: require('../../assets/Heart.png'),
  leaveGroupIcon: require('../../assets/leaveGroupIcon.png'),
  profileIcon: require('../../assets/profileIcon.png'),
  ReportIcon: require('../../assets/ReportIcon.png'),
  viewMemberIcon: require('../../assets/viewMemberIcon.png'),
  addButton: require('../../assets/addButton.png'),
};

export const FONTS = {
  Regular: 'IBMPlexSans-Regular',
  Medium: 'IBMPlexSans-Medium',
  Light: 'IBMPlexSans-Light',
  Bold: 'IBMPlexSans-Bold',
  MediumItalic: 'IBMPlexSans-MediumItalic',
  LightItalic: 'IBMPlexSans-LightItalic',
  BoldItalic: 'IBMPlexSans-BoldItalic',
};
