export const COLORS = {
  backgroundColor: '#F6F6F6',
  black: '#000000',
  grey: '#ABABAB',
  blue: '#42acf9',
  white: '#FFFFFF',
  textColor: '#151313',
  textColorGrey: '#969696',
  error: '#FE0303',
  green: '#4CCF0F',
  red: '#FE0303',
  placeholder: '#B0B0B0',
};

export const images = {
  backButton: require('../../assets/backButton.png'),
  headerIcon: require('../../assets/headerIcon.png'),
  bigAppIcon: require('../../assets/BigAppIcon.png'),
  cameraIcon: require('../../assets/cameraIcon.png'),
  dummyProfilePic: require('../../assets/dummyProfilePicture.png'),
  profileSelected: require('../../assets/porfileSelected.png'),
  profileUnselected: require('../../assets/profileUnselected.png'),
  communitySelected: require('../../assets/communitySelected.png'),
  communityUnselected: require('../../assets/communityUnselected.png'),
  search: require('../../assets/Search.png'),
  filter: require('../../assets/Filter.png'),
  postOptions: require('../../assets/postOptions.png'),
  commentsIcon: require('../../assets/Comment.png'),
  likeIcon: require('../../assets/Heart.png'),
  leaveGroupIcon: require('../../assets/leaveGroupIcon.png'),
  profileIcon: require('../../assets/profileIcon.png'),
  ReportIcon: require('../../assets/ReportIcon.png'),
  viewMemberIcon: require('../../assets/viewMemberIcon.png'),
  addButton: require('../../assets/addButton.png'),
  camera: require('../../assets/Camera.png'),
  image: require('../../assets/Image.png'),
  exploreSpaceIcon: require('../../assets/ExploreSpaceIcon.png'),
  joinGroupIcon: require('../../assets/joinGroupIcon.png'),
  alreadyInGroupIcon: require('../../assets/alreadyInGroupIcon.png'),
  plus: require('../../assets/plus.png'),
  send: require('../../assets/Send.png'),
  loaderImage: require('../../assets/splashScreenAsLoader.png'),
};

export const FONTS = {
  Regular: 'IBMPlexSans-Regular',
  Medium: 'IBMPlexSans-Medium',
  Light: 'IBMPlexSans-Light',
  Bold: 'IBMPlexSans-Bold',
  MediumItalic: 'IBMPlexSans-MediumItalic',
  LightItalic: 'IBMPlexSans-LightItalic',
  BoldItalic: 'IBMPlexSans-BoldItalic',
};
